// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEx3CRksZJiuNQPIwtcxbvS-43OOWJ5Ec',
    appId: '1:274112596634:web:00fffb7198e75bbb03ad23',
    messagingSenderId: '274112596634',
    projectId: 'test-c96ab',
    authDomain: 'test-c96ab.firebaseapp.com',
    storageBucket: 'test-c96ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfN3FgMh2brP8xqIp0riu8e2TPqN9_beA',
    appId: '1:274112596634:android:94229f1b6a40d99503ad23',
    messagingSenderId: '274112596634',
    projectId: 'test-c96ab',
    storageBucket: 'test-c96ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUyPDWYq74XMPgxm7MzPae8zVNw3HM74',
    appId: '1:274112596634:ios:d3b99b1c600db7ca03ad23',
    messagingSenderId: '274112596634',
    projectId: 'test-c96ab',
    storageBucket: 'test-c96ab.appspot.com',
    iosClientId: '274112596634-akank7rgf7tl2bia1hqaj7ibp4sb1a74.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummyapp',
  );
}
